name: Get App Token

on:
  pull_request:
  workflow_dispatch:

jobs:
  get-app-token:
    runs-on: ubuntu-latest
    steps:
      - name: Get App Token
        uses: suchithrzp/create-github-app-token@v1.0.5
        id: app-token
        with:
          app-id: ${{ secrets.RELEASER_APP_ID }}
          private-key: ${{ secrets.RELEASER_APP_PRIVATE_KEY }}
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
